### ISSUE TITLE
can you increasw the cps to 40 or 35cps

### ISSUE THREAD

**Issue by 192881ANAJ** [Ruffian7/7Clicker#9]
I want the autoclicker to be increased to 30 to 40cps is there any way?? or can you tell me how to expand the cps to 30 or 40

**Comment by psynyde** [comment]
> I want the autoclicker to be increased to 30 to 40cps is there any way?? or can you tell me how to expand the cps to 30 or 40 

Use the numbers instead of the slider..you can set max to 100 (maybe)...just click on the number and type with keyboard..for both max and min cps

**Comment by 192881ANAJ** [comment]
> > I want the autoclicker to be increased to 30 to 40cps is there any way?? or can you tell me how to expand the cps to 30 or 40
> 
> Use the numbers instead of the slider..you can set max to 100 (maybe)...just click on the number and type with keyboard..for both max and min cps

ty imma try this and then msg ya

**Comment by 192881ANAJ** [comment]
> > I want the autoclicker to be increased to 30 to 40cps is there any way?? or can you tell me how to expand the cps to 30 or 40
> 
> Use the numbers instead of the slider..you can set max to 100 (maybe)...just click on the number and type with keyboard..for both max and min cps

thanks it worked

**Comment by psynyde** [comment]
> thanks it worked

My pleasure.. please close the issue if you don't have any further issues/ questions 💖
